# Generated by Django 3.2.6 on 2021-08-15 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата старта')),
                ('finish_date', models.DateField(verbose_name='Дата окончания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
                ('passed', models.ManyToManyField(blank=True, related_name='passed_interviews', to=settings.AUTH_USER_MODEL, verbose_name='Пройдено')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_first', models.BooleanField(default=False, verbose_name='Первый')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('type_que', models.IntegerField(choices=[(1, 'Text'), (2, 'One_version'), (3, 'Several_variants')], default=1, verbose_name='Тип вопроса')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='quiz.interview', verbose_name='К опросу')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_question', to='quiz.question', verbose_name='Предыдущий')),
            ],
        ),
        migrations.CreateModel(
            name='VariantsAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вариант ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants_question', to='quiz.question', verbose_name='К вопросу')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_answers', to='quiz.interview', verbose_name='К вопросу')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='quiz.question', verbose_name='На вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
                ('variant', models.ManyToManyField(blank=True, related_name='answer_variants', to='quiz.VariantsAnswer', verbose_name='Вариант')),
            ],
        ),
    ]
